-- Admin Backup ID: 13
SET FOREIGN_KEY_CHECKS=0;

-- Table: currency_safe
INSERT INTO `currency_safe` (`id`,`user_id`,`admin_id`,`usd`,`afn`,`eur`,`irr`,`aed`,`try`,`cny`,`pkr`,`gbp`,`jpy`,`sar`,`inr`,`created_at`,`updated_at`) VALUES ('28','13','13','0.00','10000.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','0.00','2026-01-22 15:11:41','2026-01-22 15:11:41') ON DUPLICATE KEY UPDATE `id`=`id`, `user_id`=VALUES(`user_id`), `admin_id`=VALUES(`admin_id`), `usd`=VALUES(`usd`), `afn`=VALUES(`afn`), `eur`=VALUES(`eur`), `irr`=VALUES(`irr`), `aed`=VALUES(`aed`), `try`=VALUES(`try`), `cny`=VALUES(`cny`), `pkr`=VALUES(`pkr`), `gbp`=VALUES(`gbp`), `jpy`=VALUES(`jpy`), `sar`=VALUES(`sar`), `inr`=VALUES(`inr`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_currency_safe_28 = LAST_INSERT_ID();

-- Table: customers
INSERT INTO `customers` (`id`,`fullname`,`image`,`city`,`phone`,`idcard_number`,`account_number`,`whatsapp_number`,`type`,`id_card_image`,`password`,`created_by`,`user_id`,`admin_id`,`created_at`,`updated_at`,`related_customer_id`) VALUES ('18','مجید',NULL,'هرات','93790506000','217467432432','6696693113117947','93790506000','مشتری عادی',NULL,'$2y$12$O1rGR9RC./2ZdclXBIbjGOSqs9dyDijt9qjAGOHRLlep9yQnMSmAm',NULL,'13','13','2026-01-22 11:54:53','2026-01-22 11:54:53',NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `fullname`=VALUES(`fullname`), `image`=VALUES(`image`), `city`=VALUES(`city`), `phone`=VALUES(`phone`), `idcard_number`=VALUES(`idcard_number`), `account_number`=VALUES(`account_number`), `whatsapp_number`=VALUES(`whatsapp_number`), `type`=VALUES(`type`), `id_card_image`=VALUES(`id_card_image`), `password`=VALUES(`password`), `created_by`=VALUES(`created_by`), `user_id`=VALUES(`user_id`), `admin_id`=VALUES(`admin_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`), `related_customer_id`=VALUES(`related_customer_id`);
SET @last_id_customers_18 = LAST_INSERT_ID();
INSERT INTO `customers` (`id`,`fullname`,`image`,`city`,`phone`,`idcard_number`,`account_number`,`whatsapp_number`,`type`,`id_card_image`,`password`,`created_by`,`user_id`,`admin_id`,`created_at`,`updated_at`,`related_customer_id`) VALUES ('19','صفی الله',NULL,'هرات','93790201031','2432343242','6728641669727577','93790201031','مشتری عادی',NULL,'$2y$12$6cIWHzcJ1sZITEALs2oLe.zgRE0nJ6f8cmDIgyaOvcxjV/u.p6uwO',NULL,'13','13','2026-01-22 11:55:41','2026-01-22 11:55:41','18') ON DUPLICATE KEY UPDATE `id`=`id`, `fullname`=VALUES(`fullname`), `image`=VALUES(`image`), `city`=VALUES(`city`), `phone`=VALUES(`phone`), `idcard_number`=VALUES(`idcard_number`), `account_number`=VALUES(`account_number`), `whatsapp_number`=VALUES(`whatsapp_number`), `type`=VALUES(`type`), `id_card_image`=VALUES(`id_card_image`), `password`=VALUES(`password`), `created_by`=VALUES(`created_by`), `user_id`=VALUES(`user_id`), `admin_id`=VALUES(`admin_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`), `related_customer_id`=VALUES(`related_customer_id`);
SET @last_id_customers_19 = LAST_INSERT_ID();

-- Table: journal
INSERT INTO `journal` (`id`,`customer_id`,`user_id`,`admin_id`,`currency`,`type`,`account_type`,`amount`,`date`,`balance`,`description`,`transaction_id`,`account_to_account_id`,`conversion_in_account_id`,`conversion_transfer_id`,`buysell_id`,`withdrawbank_id`,`changerdeals_id`,`created_at`,`updated_at`,`is_sell_table`,`withdraw_id`) VALUES ('340','19','13','13','afn','رسید','نقدی','10000.00','1404-11-02','10000.00','رسید شد.','722',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-22 15:11:41','2026-01-22 15:11:41','0',NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `customer_id`=VALUES(`customer_id`), `user_id`=VALUES(`user_id`), `admin_id`=VALUES(`admin_id`), `currency`=VALUES(`currency`), `type`=VALUES(`type`), `account_type`=VALUES(`account_type`), `amount`=VALUES(`amount`), `date`=VALUES(`date`), `balance`=VALUES(`balance`), `description`=VALUES(`description`), `transaction_id`=VALUES(`transaction_id`), `account_to_account_id`=VALUES(`account_to_account_id`), `conversion_in_account_id`=VALUES(`conversion_in_account_id`), `conversion_transfer_id`=VALUES(`conversion_transfer_id`), `buysell_id`=VALUES(`buysell_id`), `withdrawbank_id`=VALUES(`withdrawbank_id`), `changerdeals_id`=VALUES(`changerdeals_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`), `is_sell_table`=VALUES(`is_sell_table`), `withdraw_id`=VALUES(`withdraw_id`);
SET @last_id_journal_340 = LAST_INSERT_ID();

-- Table: online_notification_user
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('24','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_24 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('25','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_25 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('28','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_28 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('29','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_29 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('30','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_30 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('31','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_31 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('32','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_32 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('33','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_33 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('34','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_34 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('35','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_35 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('36','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_36 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('37','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_37 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('38','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_38 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('39','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_39 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('40','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_40 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('41','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_41 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('42','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_42 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('43','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_43 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('44','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_44 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('45','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_45 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('46','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_46 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('47','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_47 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('48','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_48 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('49','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_49 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('50','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_50 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('51','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_51 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('52','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_52 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('53','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_53 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('54','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_54 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('55','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_55 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('56','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_56 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('57','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_57 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('58','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_58 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('59','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_59 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('60','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_60 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('61','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_61 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('62','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_62 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('63','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_63 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('64','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_64 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('65','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_65 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('66','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_66 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('67','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_67 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('68','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_68 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('69','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_69 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('70','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_70 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('71','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_71 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('72','9','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_72 = LAST_INSERT_ID();
INSERT INTO `online_notification_user` (`id`,`online_notification_id`,`user_id`,`created_at`,`updated_at`) VALUES ('73','10','13',NULL,NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `online_notification_id`=VALUES(`online_notification_id`), `user_id`=VALUES(`user_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`);
SET @last_id_online_notification_user_73 = LAST_INSERT_ID();

-- Table: transactions
INSERT INTO `transactions` (`id`,`customer_id`,`user_id`,`admin_id`,`withdrawbank_id`,`changerdeal_id`,`conversion_transfer_id`,`conversion_in_account_id`,`account_to_id`,`currency`,`zone`,`by`,`amount`,`type`,`account_type`,`date`,`description`,`transaction_file`,`created_at`,`updated_at`,`remittance_id`) VALUES ('722','19','13','13',NULL,NULL,NULL,NULL,NULL,'afn','هرات',NULL,'10000.00','رسید','نقدی','1404-11-02','رسید شد.',NULL,'2026-01-22 15:11:41','2026-01-22 15:11:41',NULL) ON DUPLICATE KEY UPDATE `id`=`id`, `customer_id`=VALUES(`customer_id`), `user_id`=VALUES(`user_id`), `admin_id`=VALUES(`admin_id`), `withdrawbank_id`=VALUES(`withdrawbank_id`), `changerdeal_id`=VALUES(`changerdeal_id`), `conversion_transfer_id`=VALUES(`conversion_transfer_id`), `conversion_in_account_id`=VALUES(`conversion_in_account_id`), `account_to_id`=VALUES(`account_to_id`), `currency`=VALUES(`currency`), `zone`=VALUES(`zone`), `by`=VALUES(`by`), `amount`=VALUES(`amount`), `type`=VALUES(`type`), `account_type`=VALUES(`account_type`), `date`=VALUES(`date`), `description`=VALUES(`description`), `transaction_file`=VALUES(`transaction_file`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`), `remittance_id`=VALUES(`remittance_id`);
SET @last_id_transactions_722 = LAST_INSERT_ID();

-- Table: users
INSERT INTO `users` (`id`,`name`,`lastname`,`sarafi_name`,`address`,`phone`,`zone`,`username`,`password`,`role`,`user_limition`,`status`,`admin_id`,`created_at`,`updated_at`,`phone2`,`phone3`,`address2`,`address3`,`user_image`,`whatsapp_notification`) VALUES ('13','ali','ahmadi','زرین','هرات - خراسان مارکت -طبق سوم دوکان نمبر  ۲۳','93794134020','هرات','ali','$2y$12$gMOfXnpcuu8XSfi4SNTlCOgOVODPOYV3vKVaLX./mpX1XvGF0GhIu','admin','4','1',NULL,'2025-11-08 12:00:10','2026-01-22 12:00:59',NULL,'93794134020','هرات - آریا مارکت -طبق سوم دوکان نمبر  ۴۳','هرات - راغی مارکت -طبق سوم دوکان نمبر  ۶۷','users/user_9_6970ad16d6c84.webp','1') ON DUPLICATE KEY UPDATE `id`=`id`, `name`=VALUES(`name`), `lastname`=VALUES(`lastname`), `sarafi_name`=VALUES(`sarafi_name`), `address`=VALUES(`address`), `phone`=VALUES(`phone`), `zone`=VALUES(`zone`), `username`=VALUES(`username`), `password`=VALUES(`password`), `role`=VALUES(`role`), `user_limition`=VALUES(`user_limition`), `status`=VALUES(`status`), `admin_id`=VALUES(`admin_id`), `created_at`=`created_at`, `updated_at`=VALUES(`updated_at`), `phone2`=VALUES(`phone2`), `phone3`=VALUES(`phone3`), `address2`=VALUES(`address2`), `address3`=VALUES(`address3`), `user_image`=VALUES(`user_image`), `whatsapp_notification`=VALUES(`whatsapp_notification`);
SET @last_id_users_13 = LAST_INSERT_ID();

SET FOREIGN_KEY_CHECKS=1;
